'use strict';
const path = require('node:path');
const { buildSync } = require('esbuild');

// Keep the deployable bundle in the repository so Vercel's existing static
// project needs no custom build step or experimental require(ESM) setting.
buildSync({
  absWorkingDir: path.resolve(__dirname, '..'),
  entryPoints: ['server/blog-render.js'],
  outfile: 'server/blog-render.bundle.cjs',
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22',
  banner: { js: '// Generated by npm run build:blog. Edit server/blog-render.js, then rebuild.' },
  logLevel: 'info'
});
